---
version: '3.8'
services:

  multibot:
    image: paper2code/telegram-multibot:latest
    container_name: ${NAMESPACE}-multibot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 8087:8087
    volumes:
    - ./shared/config/multibot-docker.toml:/usr/local/etc/multibot.toml
    - multibot-data:/usr/local/shared/data
    - multibot-media:/usr/bin/shared/medias
    networks:
    - internal
    - web
    command: ["tg-multibot"]

  mysql:
    image: paper2code/mysql-multi:5-ubuntu
    build:
      context: .docker/mysql5-multi
      dockerfile: Dockerfile
    container_name: ${NAMESPACE}-multidb
    ports:
    - 3309:3306
    volumes:
    - db-data:/var/lib/mysql
    - ./.config/mysql/milvus.cnf:/etc/mysql/conf.d/my.cnf
    # - ${PWD}/shared/export/:/var/lib/mysql/export/
    networks:
    - internal
    - web
    environment:
      MYSQL_MULTIPLE_DATABASES: paper2telegram,paper2milvus
      MYSQL_PASSWORD: ${P2TG_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${P2TG_MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${P2TG_MYSQL_USER}
    restart: unless-stopped

  elastic:
    image: elasticsearch:7.6.2
    container_name: ${NAMESPACE}-elasticsearch
    networks:
    - internal
    environment:
    - discovery.type=single-node
    volumes:
    - es-data:/usr/share/elasticsearch/data
    ulimits:
      nproc: 65535
      nofile:
         soft: 65535
         hard: 65535
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped

networks:
  internal:
    driver: bridge
  web:
    external: true

volumes:
  multibot-data:
  multibot-media:
  db-data:
  es-data:
