[main]
  api_key = ""
  plugin_dir = "../../shared/plugins"
  debug = true

[db]
  driver = "sqlite3"
  name = "../../shared/data/multibot.db"
  user = ""
  password = ""
  host = ""
  port = ""
  secure = false

[log]
  level = "info"
